// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SporiumAPI.Data;

#nullable disable

namespace SporiumAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218132610_SifreDuzeltmeFinal")]
    partial class SifreDuzeltmeFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SporiumAPI.BlogBegeni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogBegeniler");
                });

            modelBuilder.Entity("SporiumAPI.BlogYorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UyeId");

                    b.ToTable("BlogYorumlar");
                });

            modelBuilder.Entity("SporiumAPI.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("SporiumAPI.Models.Gider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Tutar")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Giderler");
                });

            modelBuilder.Entity("SporiumAPI.Models.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("longtext");

                    b.Property<string>("AntrenmanProgrami")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiyetProgrami")
                        .HasColumnType("longtext");

                    b.Property<string>("Durum")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mesajlar")
                        .HasColumnType("longtext");

                    b.Property<string>("Paket")
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .HasColumnType("longtext");

                    b.Property<string>("Sifre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Uyeler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Semih Gök",
                            Durum = "Aktif",
                            Email = "semihgok5025@gmail.com",
                            Fiyat = 0m,
                            KayitTarihi = new DateTime(2026, 2, 18, 16, 26, 9, 710, DateTimeKind.Local).AddTicks(5543),
                            Rol = "Admin",
                            Sifre = "25422542sG!."
                        });
                });

            modelBuilder.Entity("SporiumAPI.BlogBegeni", b =>
                {
                    b.HasOne("SporiumAPI.Models.Blog", null)
                        .WithMany("Begeniler")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SporiumAPI.BlogYorum", b =>
                {
                    b.HasOne("SporiumAPI.Models.Blog", null)
                        .WithMany("Yorumlar")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SporiumAPI.Models.Uye", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("SporiumAPI.Models.Blog", b =>
                {
                    b.Navigation("Begeniler");

                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
